#!/usr/bin/env python3
"""
intercom_to_mintlify.py - Pull individual Intercom articles by ID, convert the
HTML body to MDX, write them into a Mintlify page tree, and wire them into
docs.json navigation as tab -> menu -> group -> page.

DEPENDENCIES: none. Python 3.8+ standard library only.

Usage:
    python intercom_to_mintlify.py                 # fetch + write + update docs.json
    python intercom_to_mintlify.py --dry-run       # show what would happen, write nothing
    python intercom_to_mintlify.py --download-images
    mint dev                                       # then preview on localhost:3000

To add more articles later, just add entries to ARTICLE_MAP below.
"""

# ===========================================================================
#  1. BEARER TOKEN
#  ---------------------------------------------------------------------
#  Precedence:  --api-key flag  >  $INTERCOM_API_KEY env var  >  this constant
#      PowerShell:  $env:INTERCOM_API_KEY = "your_token"
# ===========================================================================
API_KEY = ""

# ===========================================================================
#  2. WHERE EACH ARTICLE GOES IN THE DOCS
#  ---------------------------------------------------------------------
#  One entry per Intercom article. The nesting produced is:
#      tab  ->  menu (item)  ->  group  ->  page
#  Add a new dict here and re-run; the script is idempotent.
# ===========================================================================
ARTICLE_MAP = [
    {
        "id": 9586885,
        "tab": "Passwordless",
        "menu": "Web - Chrome Vault",
        "group": "Admin Guides",
    },
    {
        "id": 13157388,
        "tab": "Administration",
        "menu": "Windows Login",
        "group": "Admin Guides",
    },
]

# Existing top-level `pages` / `groups` in docs.json must move into a tab,
# because Mintlify's navigation accepts either `pages` or `tabs`, never both.
EXISTING_PAGES_TAB = "Get Started"

# ===========================================================================
#  3. THEME AND PRESENTATION
#  ---------------------------------------------------------------------
#  THEME    - one of: mint, maple, palm, willow, linden, almond, aspen,
#             sequoia, luma. Set to `luma`.
#             reference config; the prose measure is capped in
#             style.css, so the theme is a styling choice only.
#  EYEBROWS - "breadcrumbs" shows the full path above each page title,
#             "section" (Mintlify's default) shows only the section name.
# ===========================================================================
THEME = "luma"
EYEBROWS = "breadcrumbs"

# Typography.
#
# oloid.help renders articles in `system-ui` - Segoe UI on Windows, SF Pro on
# macOS - and docs.json cannot express a system font stack, only a named family.
# So the family is set in style.css below and FONTS is left empty, which keeps
# the two pipelines from fighting over the same property.
#
# To use a webfont instead, put e.g. {"heading": {"family": "Inter", "weight": 700},
# "body": {"family": "Inter", "weight": 400}} here AND drop --oloid-font from
# style.css; docs.json wins only when style.css does not set font-family.
FONTS = {}

# docs.json cannot express type scale, line height or spacing rhythm, so those
# live in style.css, which Mintlify auto-loads from the repo root.
STYLE_MARKER = "/* generated by intercom_to_mintlify.py */"
STYLE_CSS = STYLE_MARKER + """
/* ==========================================================================
   Oloid documentation typography
   --------------------------------------------------------------------------
   docs.json cannot express type size: its `styling` key only carries
   `eyebrows` and `codeblocks`, and `fonts` only takes family/weight. So the
   whole scale lives here.

   The structure of a page follows oloid.help exactly (see AGENTS.md); the
   SIZE is deliberately one notch below it, because the help-centre scale
   reads large on a docs site with a sidebar:

                    oloid.help      here
       body           16px          15px
       h1 (title)     32px          27px
       h2 section     24px          19px
       h3             20px        16.5px
       h4             18px          15px
       h5             16px        13.5px
       line-height    1.53          1.60   (more leading at a smaller size)

   Every size is a variable, so "make it smaller again" is one block to edit.
   Mintlify loads style.css after its framework styles, so these rules win.
   Content renders inside .mdx-content (Tailwind `prose`).
   ========================================================================== */

:root {
  /* matches oloid.help, which sets no webfont and inherits the OS UI face */
  --oloid-font: system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial,
                sans-serif, "Apple Color Emoji", "Segoe UI Emoji";

  --oloid-body-size: 15px;
  --oloid-leading: 1.6;
  /* Column split. Only the two sidebars are sized; the article slot is the
     flex-1 remainder, so it lands on 2/3 without being set anywhere. The two
     values are the SAME width stated against different parents, so they must
     be changed together: --oloid-rail against the viewport, and
     --oloid-rail-of-main against <main> (the 83.3333% the fixed nav leaves,
     hence 16.6667 / 83.3333 = 20%). */
  --oloid-rail: 16.6667%;             /* each sidebar, of the viewport  = 1/6 */
  --oloid-rail-of-main: 20%;          /* the same 1/6, measured in <main>     */
  /* Width of the text column itself, centred inside that 2/3 slot. */
  --oloid-article-measure: min(100%, 100ch);

  --oloid-h1: 27px;
  --oloid-h2: 19px;
  --oloid-h3: 16.5px;
  --oloid-h4: 15px;
  --oloid-h5: 13.5px;

  --oloid-small: 13.5px;      /* callouts, tables */
  --oloid-nav: 12px;          /* sidebar entries, group headings, tab bar */
  --oloid-toc: 12px;          /* the "On this page" rail */
  --oloid-eyebrow: 11px;      /* breadcrumbs */

  --oloid-hairline: rgb(0 0 0 / 0.10);
}

:root[class~="dark"] { --oloid-hairline: rgb(255 255 255 / 0.14); }

/* --- body copy ---------------------------------------------------------- */
#content-area,
.mdx-content {
  font-family: var(--oloid-font);
  font-size: var(--oloid-body-size);
  line-height: var(--oloid-leading);
}

.mdx-content p,
.mdx-content li { text-wrap: pretty; }

/* --- layout: 2/3 article, 1/6 + 1/6 sidebars --------------------------
   luma pins the nav with `position: fixed; width: 14rem` and clears it by
   giving #body-content `lg:pl-56`. On top of that correct offset it also
   gives #content-area `lg:ml-[max(0px, calc(50vw - 348px - 14rem))]`, purely
   to centre the column - 388px of left margin at 1920px. That extra margin
   was the empty band on the left, and it is removed here.

   The DOM inside <main> is:

       main#content-container            flex
         div.flex-1.min-w-0              <- the article slot
           #content-area                 <- title + body + footer
         #content-side-layout            <- the rail, xl and up only

   The rail is a sibling of the SLOT, not of #content-area, so the slot is
   already "everything main has minus the rail". Sizing the article as a
   fraction of the slot would subtract the rail twice. The slot is therefore
   left at its natural flex-1 width, which works out as:

       left nav    1/6   16.6667vw   (fixed, plus the matching pl on wrapper)
       slot        2/3   66.6667vw   (flex-1: whatever is left)
       rail        1/6   16.6667vw   (20% of <main>)

   justify-items centres the article inside that slot. It is a grid property,
   so the slot is switched from flex to a single-column grid for it to apply.
   ------------------------------------------------------------------- */
@media (min-width: 1024px) {
  /* left nav, and the padding that reserves room for it, move together */
  #sidebar-content { width: var(--oloid-rail); }
  #body-content    { padding-left: var(--oloid-rail); }

  #content-container > div.flex-1.min-w-0 {
    display: grid;
    grid-template-columns: 100%;
    justify-items: center;
  }

  /* the article fills the slot up to a line length, then stops and centres,
     so the gutters grow on a wide screen instead of the text running on */
  #content-area {
    width: 100%;
    max-width: var(--oloid-article-measure);
    margin-left: 0;
    margin-right: 0;
    padding-left: 2rem;
    padding-right: 2rem;
  }
}

/* xl and up the rail appears. #content-side-layout is its wrapper and a
   direct child of <main>; it carries w-[18rem] and max-w-[28rem], both of
   which are replaced so the rail scales with the window. */
@media (min-width: 1280px) {
  #content-side-layout {
    width: var(--oloid-rail-of-main);
    max-width: none;
  }
}

/* --- heading scale ------------------------------------------------------ */
/* Pages never contain an H1: the frontmatter `title` is the only one, so the
   first body heading is an H2 rather than a second full-size title. */
#content-area h1,
.mdx-content h1 {
  font-family: var(--oloid-font);
  font-size: var(--oloid-h1); line-height: 1.22; font-weight: 700;
  letter-spacing: -0.018em; margin-bottom: 0.45em;
}
.mdx-content h2 {
  font-family: var(--oloid-font);
  font-size: var(--oloid-h2); line-height: 1.25; font-weight: 600;
  letter-spacing: -0.011em; margin-top: 1.9em; margin-bottom: 0.6em;
}
.mdx-content h3 {
  font-family: var(--oloid-font);
  font-size: var(--oloid-h3); line-height: 1.32; font-weight: 600;
  letter-spacing: -0.007em; margin-top: 1.65em; margin-bottom: 0.5em;
}
.mdx-content h4 {
  font-family: var(--oloid-font);
  font-size: var(--oloid-h4); line-height: 1.4; font-weight: 600;
  margin-top: 1.4em; margin-bottom: 0.45em;
}
.mdx-content h5 {
  font-family: var(--oloid-font);
  font-size: var(--oloid-h5); line-height: 1.45; font-weight: 600;
  margin-top: 1.25em; margin-bottom: 0.4em;
}
/* never push the first block away from the page title */
.mdx-content > :first-child { margin-top: 0; }

/* the description under the page title */
#content-area > header p { font-size: calc(var(--oloid-body-size) + 1px); line-height: 1.45; }

/* --- lists: these docs are mostly numbered procedures -------------------- */
/* Every step, its screenshot, its note and its sub-steps share one left edge.
   Generated MDX indents continuation lines to the marker's content column, so
   the browser only has to keep the padding consistent. */
.mdx-content ol,
.mdx-content ul { padding-left: 1.5em; }
.mdx-content li { margin-top: 0.28em; margin-bottom: 0.28em; }
.mdx-content li::marker { font-weight: 600; }

/* a list item that contains a callout or an image is "loose": MDX wraps its
   text in <p>. Trim those margins so a loose item still reads as one step. */
.mdx-content li > p { margin-top: 0.25em; margin-bottom: 0.25em; }
.mdx-content li > p:first-child { margin-top: 0; }
.mdx-content li > p:last-child { margin-bottom: 0; }

/* nested steps need to read as subordinate, not as a new list */
.mdx-content li > ol,
.mdx-content li > ul { margin-top: 0.35em; margin-bottom: 0.6em; }

/* --- screenshots -------------------------------------------------------- */
/* Images are plain markdown rather than <Frame> so that they align with the
   step they belong to; the frame look is restored here instead. */
.mdx-content img {
  border-radius: 8px;
  border: 1px solid var(--oloid-hairline);
  margin-top: 0.55em; margin-bottom: 0.55em;
}
.mdx-content > p > img { margin-top: 0.9em; margin-bottom: 1.1em; }
.mdx-content .frame { margin-top: 1.1em; margin-bottom: 1.3em; }
.mdx-content li .frame { margin-top: 0.55em; margin-bottom: 0.75em; }

/* --- callouts ----------------------------------------------------------- */
/* Notes sit inside numbered steps, so they must not tower over the step text.
   Mintlify renders them as <div class="callout ..." data-callout-type="note">. */
.mdx-content .callout {
  font-size: var(--oloid-small); line-height: 1.5;
  padding: 0.7rem 0.95rem; border-radius: 0.6rem; margin: 0.7em 0;
}
.mdx-content li .callout { margin-top: 0.4em; margin-bottom: 0.4em; }
.mdx-content .callout p { margin-top: 0; margin-bottom: 0; }
.mdx-content .callout ul,
.mdx-content .callout ol { margin-top: 0.2em; margin-bottom: 0.2em; }
.mdx-content .callout li { margin-top: 0.12em; margin-bottom: 0.12em; }

/* --- inline code and tables --------------------------------------------- */
.mdx-content :not(pre) > code {
  font-size: 0.86em; font-weight: 500;
  padding: 0.12em 0.34em; border-radius: 0.3rem;
}
.mdx-content table { font-size: var(--oloid-small); }
.mdx-content th { font-weight: 600; }

/* --- navigation: Intercom titles are long, let them wrap cleanly -------- */
#navigation-items { font-family: var(--oloid-font); }

/* Mintlify sizes the whole sidebar from one Tailwind utility on an inner
   wrapper - <div class="text-sm ..."> - and the links, group headers and
   dropdown buttons all inherit from it. Overriding that wrapper is what
   actually changes the sidebar; the rest are listed so a future markup change
   cannot quietly put one row back to 14px. !important because these compete
   with utility classes, not with ordinary rules. */
#navigation-items,
#navigation-items .text-sm,
#navigation-items a,
#navigation-items button,
#navigation-items h5,
#navigation-items .sidebar-group-header {
  font-size: var(--oloid-nav) !important;
}

#navigation-items a { line-height: 1.4; }

/* --- table of contents (the right rail) ---------------------------------
   Sized the same way and for the same reason as the left sidebar: Mintlify
   puts a `text-sm` utility on the scroll wrapper and every entry inherits it,
   so the wrapper is what has to be overridden. The links, the "On this page"
   heading and the nested H3 entries are all named as well, so a markup change
   cannot quietly restore one row to 14px. */
#content-side-layout,
#table-of-contents,
#table-of-contents .text-sm,
#table-of-contents a,
#table-of-contents li,
#table-of-contents p,
#table-of-contents h5 {
  font-size: var(--oloid-toc) !important;
}

#table-of-contents { font-family: var(--oloid-font); }
#table-of-contents a { line-height: 1.4; }

/* --- sidebar inner padding ---------------------------------------------
   Two paddings push the sidebars away from the article for no good reason
   once the columns are a third of the screen:

     left nav   the scroll viewport carries `pl-5 pr-5`; the pr-5 is dropped
                so entries run to the nav's own right edge. Its id is
                generated per render (base-ui-_R_..._-viewport), so it is
                matched on its two padding classes instead.
     right rail #content-side-layout carries `pl-8 pr-5 pt-4`; the pl-8 is
                dropped so the rail sits closer to the article.

   Only the one side is zeroed in each case - the outer padding stays, or
   the text would touch the window edge.
   ----------------------------------------------------------------------- */
#sidebar-content .pl-5.pr-5 { padding-right: 0; }
#content-side-layout { padding-left: 0; }

/* --- print / PDF --------------------------------------------------------
   The "Download PDF" item in the contextual menu produces a PDF of the
   rendered page, so the screen layout above would otherwise carry the nav,
   the rail and the sticky bar into the file. Print gets a single
   full-bleed column instead.
   ----------------------------------------------------------------------- */
@media print {
  /* chrome that means nothing on paper */
  #sidebar-content,
  #content-side-layout,
  #navigation-items,
  #footer,
  [class*="breadcrumb"] { display: none !important; }

  /* undo the three-column layout: one column, full width */
  #body-content { padding-left: 0 !important; }
  #content-container > div.flex-1.min-w-0 { display: block !important; }
  #content-area {
    width: 100% !important;
    max-width: 100% !important;
    padding-left: 0 !important;
    padding-right: 0 !important;
  }

  /* keep a step and its screenshot on the same sheet where possible */
  .mdx-content li,
  .mdx-content .callout,
  .mdx-content img { break-inside: avoid; page-break-inside: avoid; }
  .mdx-content h2,
  .mdx-content h3,
  .mdx-content h4 { break-after: avoid; page-break-after: avoid; }

  .mdx-content img { max-width: 100%; height: auto; }

  /* ink-friendly body text */
  #content-area, .mdx-content { font-size: 11pt; line-height: 1.45; }
}

/* --- breadcrumbs -------------------------------------------------------- */
[class*="breadcrumb"] { font-size: var(--oloid-eyebrow); letter-spacing: 0.01em; }

/* --- topbar search and assistant ----------------------------------------
   Mintlify stretches the search entry and the "Ask AI" input to fill the
   topbar, which on a wide screen is a very long pill for a two-word query.
   Both are capped here and pushed to the right of the bar.

   The width is one variable. The selector list is deliberately broad because
   Mintlify renders the pair differently per theme and version: `luma` uses
   #search-bar-entry for the search trigger and #assistant-entry for Ask AI,
   older builds wrap them in #topbar-search. Extra selectors that match
   nothing cost nothing; the alternative is the bar silently going back to
   full width on the next CLI upgrade.
   ----------------------------------------------------------------------- */
:root { --oloid-search-width: 260px; }

#search-bar-entry,
#assistant-entry,
#topbar-search,
[id^="search-bar"],
[class*="search-bar"] {
  max-width: var(--oloid-search-width) !important;
  width: 100%;
  margin-left: auto;          /* sit against the right-hand controls */
}

/* the flex parent otherwise re-expands the child it is sizing */
#topbar :is(#search-bar-entry, #assistant-entry) { flex: 0 1 var(--oloid-search-width); }

/* below lg the topbar collapses to an icon row - leave that alone */
@media (max-width: 1023px) {
  #search-bar-entry,
  #assistant-entry,
  #topbar-search { max-width: none !important; }
}
"""

# ---------------------------------------------------------------------------
#  Navigation chrome
#  ---------------------------------------------------------------------
#  docs.json has no size or density controls - `styling` carries only
#  `eyebrows` and `codeblocks`, and `fonts` only takes family/weight. What it
#  can do for a lighter page is carry less chrome, so the starter kit's
#  leftovers are stripped: every anchor, navbar link, button and social that
#  still points at mintlify.com belongs to the template, not to Oloid.
#
#  Anything pointing at a real Oloid URL is left alone, so once you fill these
#  in the script stops touching them.
# ---------------------------------------------------------------------------
SITE_NAME = "Oloid"                        # only used if the name is still the starter default
PLACEHOLDER_HOSTS = ("mintlify.com", "mintlify.dev", "@mintlify.com")

# The per-page "open in..." toolbar. Eight entries make a crowded strip above
# every article; these cover copying, viewing source, the PDF download and
# the two assistants people actually use. `download-pdf` is Mintlify's own
# option - it renders a "Download PDF" item that prints the current page, so
# no custom button or script is needed.
CONTEXTUAL_OPTIONS = ["copy", "view", "download-pdf", "claude", "chatgpt"]

# Icons by navigation label. A value is either a Font Awesome name ("gear") or
# the full form {"name": ..., "library": "fontawesome"|"lucide"|"tabler",
# "style": ...}. Brand logos need the explicit "brands" style.
ICONS = {
    # tabs
    "Passwordless": "fingerprint",
    "Administration": "gear",
    "Get Started": "rocket",
    # menu items
    "Web - Chrome Vault": {"name": "chrome", "library": "fontawesome", "style": "brands"},
    "Windows Login": {"name": "windows", "library": "fontawesome", "style": "brands"},
    # groups
    "Admin Guides": "user-shield",
    "User Guides": "user",
}
DEFAULT_PAGE_ICON = "file-lines"

# Mintlify refuses images above this size; host bigger assets on a CDN instead.
MAX_IMAGE_BYTES = 20 * 1024 * 1024

import argparse
import hashlib
import html
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from html.parser import HTMLParser

API_ROOT = "https://api.intercom.io"
API_VERSION = "2.11"
MAX_RETRIES = 5
RETRY_BACKOFF = 2.0
IMAGE_DIR = "images/intercom"

BLOCK_TAGS = {"p", "div", "h1", "h2", "h3", "h4", "h5", "h6", "blockquote", "pre", "section"}
SKIP_TAGS = {"script", "style", "head", "meta", "link"}


# --------------------------------------------------------------------------
# HTTP
# --------------------------------------------------------------------------

class IntercomError(RuntimeError):
    pass


def request_json(url, token, timeout=30):
    req = urllib.request.Request(url, method="GET")
    req.add_header("Authorization", "Bearer %s" % token)
    req.add_header("Accept", "application/json")
    req.add_header("Intercom-Version", API_VERSION)
    req.add_header("User-Agent", "oloid-intercom-to-mintlify/1.0")

    delay = RETRY_BACKOFF
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", "replace")[:400]
            if exc.code in (401, 403):
                raise IntercomError(
                    "Auth failed (HTTP %s). Check API_KEY at the top of this file "
                    "or $INTERCOM_API_KEY.\n%s" % (exc.code, body)
                )
            if exc.code == 404:
                raise IntercomError("Article not found (HTTP 404): %s" % url)
            if exc.code == 429 or 500 <= exc.code < 600:
                sys.stderr.write("  HTTP %s, retry in %.0fs (%d/%d)\n"
                                 % (exc.code, delay, attempt, MAX_RETRIES))
                time.sleep(delay)
                delay *= 2
                continue
            raise IntercomError("HTTP %s from %s\n%s" % (exc.code, url, body))
        except (urllib.error.URLError, TimeoutError) as exc:
            sys.stderr.write("  network error (%s), retry in %.0fs (%d/%d)\n"
                             % (exc, delay, attempt, MAX_RETRIES))
            time.sleep(delay)
            delay *= 2
    raise IntercomError("Gave up on %s after %d attempts" % (url, MAX_RETRIES))


def fetch_article(article_id, token):
    url = "%s/articles/%s" % (API_ROOT, article_id)
    sys.stderr.write("GET %s\n" % url)
    return request_json(url, token)


# --------------------------------------------------------------------------
# HTML -> MDX
# --------------------------------------------------------------------------

def mdx_escape(text):
    """MDX parses { } as expressions and < as JSX. Neutralise them in prose."""
    text = text.replace("{", "&#123;").replace("}", "&#125;")
    text = text.replace("<", "&lt;").replace(">", "&gt;")
    return text


def attr_escape(value):
    """Safe for a JSX double-quoted attribute (JSX does not interpolate in strings)."""
    return (str(value or "")
            .replace("&", "&amp;")
            .replace('"', "&quot;")
            .replace("\n", " ")
            .strip())


class HtmlToMdx(HTMLParser):
    """Converts the subset of HTML that Intercom emits into Markdown/MDX."""

    def __init__(self, on_image=None, alt_prefix=""):
        super().__init__(convert_charrefs=True)
        self.on_image = on_image
        self.alt_prefix = alt_prefix
        self.figure_no = 0
        self.blocks = []
        self.stack = [[]]          # buffer stack; text lands in stack[-1]
        # Each open list records the column its markers start at, so a nested
        # list can begin exactly at its parent item's content column. Getting
        # this wrong is what makes steps, screenshots and notes drift apart.
        self.list_stack = []       # [{"tag", "n", "base"}]
        self.li_stack = []         # [{"emitted": bool, "col": int}]
        self.in_pre = False
        self.pre_lang = ""
        self.skip_depth = 0
        # Intercom wraps a standalone image in its own
        # `intercom-interblocks-image` div. Counting those is what tells a
        # screenshot apart from an icon sitting inside a sentence.
        self.image_block = 0
        self.div_image = []
        self.heading = None
        self.blockquote = 0
        self.table = None
        self.row = None
        self.images = []
        self.videos = []
        self.in_link = 0

    # -- buffer helpers ----------------------------------------------------
    def push(self):
        self.stack.append([])

    def pop(self):
        return self.pop_raw().strip()

    def pop_raw(self):
        return "".join(self.stack.pop()) if len(self.stack) > 1 else ""

    def emit(self, text, kind="block"):
        # List items keep their leading indent (nesting) and are joined to their
        # siblings with a single newline, so lists stay tight rather than loose.
        if kind == "li":
            if text.strip():
                self.blocks.append(("li", text.rstrip()))
        elif text and text.strip():
            self.blocks.append(("block", text.strip()))

    def write(self, text):
        self.stack[-1].append(text)

    def flush_block(self, prefix=""):
        text = "".join(self.stack[-1]).strip()
        self.stack[-1] = []
        if text:
            self.emit(prefix + text)

    # -- tags --------------------------------------------------------------
    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag in SKIP_TAGS:
            self.skip_depth += 1
            return
        if self.skip_depth:
            return

        if tag == "div":
            is_image_div = "intercom-interblocks-image" in (a.get("class") or "")
            self.div_image.append(is_image_div)
            if is_image_div:
                self.image_block += 1

        if tag == "br":
            self.write("  \n")
        elif tag == "hr":
            self.flush_block()
            self.emit("---")
        elif tag in ("strong", "b", "em", "i"):
            # buffered so padding can be moved outside the markers on close
            self.push()
        elif tag == "code" and not self.in_pre:
            self.write("`")
        elif tag == "pre":
            self.flush_block()
            self.in_pre = True
            self.pre_lang = ""
            self.push()
        elif tag == "a":
            self.in_link += 1
            self.push()
        elif tag == "img":
            src = a.get("src", "")
            alt = (a.get("alt") or "").strip()
            if src:
                if self.on_image:
                    src = self.on_image(src)
                self.images.append(src)
                # Plain markdown everywhere, never <Frame>. A block component
                # cannot share a step's left edge, and the rounded-border look
                # is restored in style.css instead.
                #
                # A screenshot stands on its own line; an icon sits inside a
                # sentence ("click the [gear] Settings icon") and must stay
                # there, or the sentence is cut in half. Two signals decide:
                # Intercom wraps a standalone image in its own
                # `intercom-interblocks-image` div, and anything else with text
                # already written on the line is mid-sentence.
                inline = self.image_block == 0 and bool(
                    "".join(self.stack[-1]).rstrip("\n").strip())
                if inline:
                    self.write("![%s](%s)" % (self.alt_for(alt), src))
                elif self.li_stack:
                    # own line, so emit_li indents it to the step's content column
                    if "".join(self.stack[-1]).strip():
                        self.write("\n")
                    self.write("![%s](%s)" % (self.alt_for(alt), src))
                else:
                    self.flush_block()
                    self.emit("![%s](%s)" % (self.alt_for(alt), src))
        elif tag == "iframe":
            src = a.get("src", "")
            if src:
                self.flush_block()
                self.videos.append(src)
                self.emit(self.frame_video(src, a.get("title") or ""))
            self.skip_depth += 1  # swallow any fallback content inside the iframe
        elif tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
            self.flush_block()
            self.heading = int(tag[1])
            self.push()
        elif tag == "blockquote":
            self.flush_block()
            self.blockquote += 1
        elif tag in ("ul", "ol"):
            # A nested list inside <li>: emit the parent step first, then start
            # the child list at that step's content column.
            if self.li_stack and not self.li_stack[-1]["emitted"]:
                text = self.pop()
                self.li_stack[-1]["col"] = self.emit_li(text)
                self.li_stack[-1]["emitted"] = True
                self.push()
            else:
                self.flush_block()
            base = self.li_stack[-1]["col"] if self.li_stack else 0
            self.list_stack.append({"tag": tag, "n": 0, "base": base})
        elif tag == "li":
            self.push()
            base = self.list_stack[-1]["base"] if self.list_stack else 0
            self.li_stack.append({"emitted": False, "col": base + 3})
        elif tag == "table":
            self.flush_block()
            self.table = []
        elif tag == "tr":
            self.row = []
        elif tag in ("td", "th"):
            self.push()
        elif tag in BLOCK_TAGS:
            # Intercom nests <p> inside <li>. Flushing there would drop the bullet
            # and turn every step into a loose paragraph, so keep it in the item.
            if self.li_stack:
                if "".join(self.stack[-1]).strip():
                    self.write("\n")
            else:
                self.flush_block()

    def alt_for(self, alt):
        """Intercom screenshots almost never carry alt text, so a positional
        fallback is generated rather than shipping an empty alt attribute."""
        alt = re.sub(r"\s+", " ", (alt or "")).replace("]", "").strip()
        if alt:
            return alt
        self.figure_no += 1
        return "%s - screenshot %d" % (self.alt_prefix or "Screenshot", self.figure_no)

    @staticmethod
    def frame_video(src, title):
        title_a = attr_escape(title)
        title_attr = '\n    title="%s"' % title_a if title_a else ""
        return ('<Frame>\n  <iframe\n    className="w-full aspect-video rounded-xl"\n'
                '    src="%s"%s\n    allowFullScreen\n  />\n</Frame>'
                % (attr_escape(src), title_attr))

    def emit_li(self, text):
        """Emit one list item and return the column its content starts at.

        CommonMark measures nesting from the content column, not from a fixed
        two spaces: under `1. ` that is column 3, under `- ` column 2, and under
        `10. ` column 4. Indenting to a fixed width is why screenshots and
        sub-steps used to hang off the left edge of the step they belong to.
        """
        if not self.list_stack:
            self.emit(text)
            return 0
        lst = self.list_stack[-1]
        base = lst["base"]
        if lst["tag"] == "ol":
            lst["n"] += 1
            marker = "%d. " % lst["n"]
        else:
            marker = "- "
        col = base + len(marker)
        lines = [l.strip() for l in text.splitlines() if l.strip()]
        if not lines:
            # no text before a nested list: skip the empty bullet, but keep the
            # column so the child list still indents correctly
            return col
        body = ("\n" + " " * col).join(lines)
        self.emit(" " * base + marker + body, kind="li")
        return col

    def emit_li_continuation(self, text, col):
        """Prose that follows a nested list but still belongs to the parent step."""
        lines = [l.strip() for l in text.splitlines() if l.strip()]
        if lines:
            self.emit(" " * col + ("\n" + " " * col).join(lines), kind="li")

    def handle_endtag(self, tag):
        # iframe must be checked before the skip guard: its own start tag raised
        # skip_depth, so the guard would otherwise never let it be lowered again.
        if tag in SKIP_TAGS or tag == "iframe":
            self.skip_depth = max(0, self.skip_depth - 1)
            return
        if self.skip_depth:
            return

        if tag == "div" and self.div_image:
            if self.div_image.pop():
                self.image_block = max(0, self.image_block - 1)

        if tag in ("strong", "b", "em", "i"):
            # "**Bold **next" never closes in Markdown. Keep the padding, but put
            # it outside the emphasis markers where it renders correctly.
            raw = self.pop_raw()
            inner = raw.strip()
            if inner:
                marker = "**" if tag in ("strong", "b") else "*"
                lead = raw[:len(raw) - len(raw.lstrip())]
                trail = raw[len(raw.rstrip()):]
                self.write("%s%s%s%s%s" % (lead, marker, inner, marker, trail))
            elif raw:
                self.write(raw)
        elif tag == "code" and not self.in_pre:
            self.write("`")
        elif tag == "pre":
            code = self.pop()
            self.in_pre = False
            self.emit("```%s\n%s\n```" % (self.pre_lang, code))
        elif tag == "a":
            self.in_link = max(0, self.in_link - 1)
            text = self.pop()
            href = getattr(self, "_href", "") or ""
            # Intercom wraps screenshots in a lightbox <a> pointing at the same
            # image. Unwrap those to a Frame instead of emitting a linked image.
            bare = re.fullmatch(r"!\[([^\]]*)\]\(([^)\s]+)\)", text.strip())
            if bare:
                # the image was already written by handle_starttag("img"); the
                # surrounding lightbox <a> adds nothing, so keep just the image
                self.write(text.strip())
            elif text and href:
                self.write("[%s](%s)" % (text, href))
            elif text:
                self.write(text)
            self._href = ""
        elif tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
            text = self.pop()
            if text:
                self.emit("#" * (self.heading or 2) + " " + text)
            self.heading = None
        elif tag == "blockquote":
            text = "".join(self.stack[-1]).strip()
            self.stack[-1] = []
            if text:
                self.emit("\n".join("> " + l for l in text.splitlines()))
            self.blockquote = max(0, self.blockquote - 1)
        elif tag in ("ul", "ol"):
            if self.list_stack:
                self.list_stack.pop()
        elif tag == "li":
            text = self.pop()
            entry = self.li_stack.pop() if self.li_stack else {"emitted": True, "col": 0}
            if not entry["emitted"]:
                self.emit_li(text)
            elif text:
                # Intercom puts the outcome sentence ("The pop-up box is
                # displayed.") after the sub-steps. It used to be dropped here.
                self.emit_li_continuation(text, entry["col"])
        elif tag in ("td", "th"):
            if self.row is not None:
                self.row.append(self.pop().replace("|", "\\|").replace("\n", " "))
            else:
                self.pop()
        elif tag == "tr":
            if self.table is not None and self.row:
                self.table.append(self.row)
            self.row = None
        elif tag == "table":
            self.emit_table()
        elif tag in BLOCK_TAGS:
            if self.li_stack:
                if "".join(self.stack[-1]).strip():
                    self.write("\n")
            else:
                self.flush_block()

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag not in ("br", "hr", "img"):
            self.handle_endtag(tag)

    def emit_table(self):
        rows = [r for r in (self.table or []) if any(c.strip() for c in r)]
        self.table = None
        if not rows:
            return
        width = max(len(r) for r in rows)
        rows = [r + [""] * (width - len(r)) for r in rows]
        head, body = rows[0], rows[1:]
        lines = ["| " + " | ".join(head) + " |",
                 "| " + " | ".join(["---"] * width) + " |"]
        for r in body:
            lines.append("| " + " | ".join(r) + " |")
        self.emit("\n".join(lines))

    def handle_data(self, data):
        if self.skip_depth:
            return
        if self.in_pre:
            self.write(data)
            return
        text = re.sub(r"\s+", " ", data)
        if text.strip() or (text == " " and self.stack[-1]):
            self.write(mdx_escape(text))

    # links need the href captured at start time
    def handle_starttag_a(self, attrs):
        pass

    def close(self):
        super().close()
        self.flush_block()
        out = []
        for kind, text in self.blocks:
            if not text.strip():
                continue
            # consecutive list items stay in one tight block
            if kind == "li" and out and out[-1][0] == "li":
                out[-1] = ("li", out[-1][1] + "\n" + text)
            else:
                out.append((kind, text))
        return "\n\n".join(text for _, text in out)


def html_to_mdx(body_html, on_image=None, alt_prefix=""):
    """Convert an Intercom article body to MDX text."""
    if not body_html:
        return "", [], []

    parser = HtmlToMdx(on_image=on_image, alt_prefix=alt_prefix)

    # capture <a href> since HTMLParser gives attrs only at start
    original = parser.handle_starttag

    def patched(tag, attrs):
        if tag == "a":
            parser._href = dict(attrs).get("href", "")
        original(tag, attrs)

    parser.handle_starttag = patched
    parser.feed(body_html)
    text = parser.close()

    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    return text.strip(), parser.images, parser.videos


# --------------------------------------------------------------------------
# Document template
# --------------------------------------------------------------------------
#  Every page is forced into one shape, whatever the Intercom source looked
#  like:
#
#      title / description / keywords    <- frontmatter, the page's only H1
#      ## Introduction
#      ## Prerequisites
#      ## Steps to <do the task>
#      ###   sub-procedure
#      ####    sub-sub-procedure
#      ## Additional Information          (optional)
#      ## Related Articles                (optional)
#
#  The body never contains an H1. Intercom writes its top-level sections as
#  <h1>, which rendered alongside the frontmatter title as a second 32px
#  heading - the reason pages read as oversized.
# --------------------------------------------------------------------------

# Canonical spelling for the sections the template defines. A source heading
# whose text matches a key (case-insensitively) is renamed and pinned to H2.
SECTION_ALIASES = {
    "introduction": "Introduction",
    "intro": "Introduction",
    "overview": "Introduction",
    "purpose": "Introduction",
    "prerequisite": "Prerequisites",
    "prerequisites": "Prerequisites",
    "pre-requisite": "Prerequisites",
    "pre-requisites": "Prerequisites",
    "pre requisites": "Prerequisites",
    "requirement": "Prerequisites",
    "requirements": "Prerequisites",
    "additional information": "Additional Information",
    "additional info": "Additional Information",
    "misc": "Additional Information",
    "miscellaneous": "Additional Information",
    "related article": "Related Articles",
    "related articles": "Related Articles",
    "related links": "Related Articles",
    "see also": "Related Articles",
}

# Order the template expects, used only for the audit report.
TEMPLATE_SECTIONS = ["Introduction", "Prerequisites", "Steps",
                     "Additional Information", "Related Articles"]
OPTIONAL_SECTIONS = {"Additional Information", "Related Articles"}

HEADING_RE = re.compile(r"^(#{1,6})[ \t]+(.*?)[ \t]*$")
FENCE_RE = re.compile(r"^[ \t]*(```+|~~~+)")

# "Note", "Note:", "**Note:**", "**Note**:" - Intercom uses all of them.
NOTE_LABELS = "Note|Notes|Important|Caution|Warning|Tip|Recommended|Remember"
NOTE_RE = re.compile(
    r"^(?P<indent>[ \t]*)"
    r"(?:\*\*(?P<a>" + NOTE_LABELS + r")[ \t]*:?[ \t]*\*\*[ \t]*:?"
    r"|(?P<b>" + NOTE_LABELS + r")[ \t]*:)"
    r"[ \t]*(?P<body>.*)$",
    re.I,
)
CALLOUT_FOR = {
    "note": "Note", "notes": "Note", "remember": "Note",
    "tip": "Tip", "recommended": "Tip",
    "important": "Warning", "caution": "Warning", "warning": "Warning",
}

# The visible label kept inside the callout. Mintlify draws an icon but no
# word, and oloid.help writes the word out, so it is preserved here: "Note:"
# for information, and each other kind keeps the term the author used, which
# says more than the component name does ("Important:" over "Warning:").
CALLOUT_LABEL = {
    "note": "Note", "notes": "Note", "remember": "Remember",
    "tip": "Tip", "recommended": "Recommended",
    "important": "Important", "caution": "Caution", "warning": "Warning",
}

# An already-converted callout must not be wrapped again on a second run.
CALLOUT_OPEN_RE = re.compile(r"^[ \t]*<(Note|Warning|Tip|Info|Check|Danger)\b")
CALLOUT_CLOSE_RE = re.compile(r"^[ \t]*</(Note|Warning|Tip|Info|Check|Danger)>")

KEYWORDS_TAIL_RE = re.compile(
    r"\n+(?:-{3,}[ \t]*\n+)?#{1,6}[ \t]*\*{0,2}[ \t]*Keywords?[ \t]*\*{0,2}[ \t]*:?[ \t]*\n"
    r"(?P<tail>.*)\Z",
    re.S | re.I,
)


def split_fences(body):
    """Yield (line, inside_code_fence) so transforms never touch code blocks."""
    fence = None
    for line in body.splitlines():
        m = FENCE_RE.match(line)
        if fence is None:
            if m:
                fence = m.group(1)[0]
                yield line, True
            else:
                yield line, False
        else:
            yield line, True
            if m and m.group(1)[0] == fence:
                fence = None


def anchor_slug(text):
    """Approximate Mintlify's heading anchors: lowercase, punctuation dropped."""
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text or "")
    text = re.sub(r"[*`_]+", "", text)
    text = re.sub(r"&\w+;|&#\d+;", " ", text)
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def clean_heading_text(text):
    """Headings arrive as '**Introduction**' or 'Configure Theme tab:'."""
    text = text.strip()
    text = re.sub(r"^\*{1,3}(.*?)\*{1,3}$", r"\1", text).strip()
    text = re.sub(r"[ \t]*[:：]$", "", text).strip()
    # "Configure Theme tab" and "Configure Details Tab" in one document
    text = re.sub(r"\btab\b\s*$", "Tab", text)
    text = re.sub(r"\btabs\b\s*$", "Tabs", text)
    return re.sub(r"\s+", " ", text)


def extract_keywords(body):
    """Pull the trailing Keywords block out of the body into frontmatter.

    Intercom stores them as a one-row pipe table, which markdown renders as a
    malformed header-only table - a stray box at the foot of every page.
    """
    m = KEYWORDS_TAIL_RE.search(body)
    if not m:
        return body, []

    words = []
    for line in m.group("tail").splitlines():
        line = line.strip()
        if not line or re.fullmatch(r"-{3,}", line) or line.startswith("#"):
            continue
        cells = line.strip("|").split("|") if line.startswith("|") else re.split(r"[,;]", line)
        for cell in cells:
            cell = re.sub(r"[*`]", "", cell).strip()
            if cell and not re.fullmatch(r"[-: ]+", cell):
                words.append(re.sub(r"\s+", " ", cell))

    seen, out = set(), []
    for word in words:
        if word.lower() not in seen:
            seen.add(word.lower())
            out.append(word)
    return body[:m.start()].rstrip(), out


def normalize_headings(body, mirror=False):
    """Strip bold from headings and shift the document so its shallowest
    heading is H2 - never H1, which would render a second 32px title under the
    frontmatter one.

    `mirror=True` is the oloid.help-faithful mode: headings keep their own text
    and their own relative depth. Nothing is renamed to a template section and
    nothing is promoted, so the page reads exactly as the help centre does.
    """
    levels = [len(m.group(1)) for line, fenced in split_fences(body)
              if not fenced for m in [HEADING_RE.match(line)] if m]
    shift = (2 - min(levels)) if levels else 0

    out = []
    for line, fenced in split_fences(body):
        m = HEADING_RE.match(line) if not fenced else None
        if not m:
            out.append(line)
            continue
        level, text = len(m.group(1)), clean_heading_text(m.group(2))
        if not text:
            continue
        canonical = None if mirror else SECTION_ALIASES.get(text.lower())
        if canonical:
            # a template section is always top level, whatever Intercom used
            text, level = canonical, 2
        elif not mirror and re.match(r"^steps?\b|^how to\b|^procedure\b", text, re.I):
            level = 2
        else:
            level = min(6, max(2, level + shift))
        out.append("#" * level + " " + text)
    return "\n".join(out)


LIST_ITEM_RE = re.compile(r"^(?P<indent>[ \t]*)(?P<marker>[-*+]|\d+[.)])[ \t]+(?P<text>.*)$")


def frames_to_images(body):
    """Unwrap <Frame><img/></Frame> back to plain markdown.

    A Frame is a block component and cannot share a step's left edge, so a
    screenshot inside a procedure drifts back to the margin. Plain images
    indent with their step; style.css restores the rounded border.
    Video frames (<Frame><iframe/></Frame>) are left alone.
    """
    def repl(match):
        block = match.group(0)
        src = re.search(r'src="([^"]*)"', block)
        if not src:
            return block
        alt = re.search(r'alt="([^"]*)"', block)
        caption = re.search(r'caption="([^"]*)"', block)
        label = (alt.group(1) if alt else "") or (caption.group(1) if caption else "")
        label = html.unescape(label).replace("]", "").strip()
        return "![%s](%s)" % (label, html.unescape(src.group(1)))

    return re.sub(r"<Frame\b[^>]*>\s*<img\b[^>]*/>\s*</Frame>", repl, body, flags=re.S)


def reindent_lists(body):
    """Re-indent every list to its parent's content column.

    CommonMark nests from the content column: under `1. ` that is column 3, and
    under `- ` column 2. Content indented a flat two spaces under `1. ` is one
    column short, so sub-steps, screenshots and outcome sentences break out of
    the step they belong to. This recomputes the columns from the source
    structure and is safe to run over an already-correct document.
    """
    out, stack = [], []
    jsx = None          # a callout already in the file moves as one block
    for line, fenced in split_fences(body):
        if fenced:
            out.append(line)
            continue
        raw = line.replace("\t", "    ")
        stripped = raw.strip()
        if not stripped:
            out.append("")
            continue

        indent = len(raw) - len(raw.lstrip(" "))

        # Inside a JSX block, shift every line by the same amount instead of
        # re-indenting each one, or the component's inner lines collapse onto
        # its opening tag and any bullets inside it get treated as steps.
        if jsx is not None:
            out.append(" " * max(0, indent + jsx["delta"]) + stripped)
            if stripped.startswith("</" + jsx["tag"]) and indent <= jsx["src"]:
                jsx = None
            continue

        # An opening JSX tag starts a protected block, at any indent. Checked
        # before the list and top-level branches so that a callout sitting at
        # the margin still shields the bullets written inside it.
        open_tag = re.match(r"<([A-Z][A-Za-z0-9]*)\b", stripped)
        if open_tag and not stripped.endswith("/>") \
                and not stripped.endswith("</%s>" % open_tag.group(1)):
            if indent == 0 or not stack:
                target = indent if stack else 0
            else:
                target = stack[-1]["content"]
            jsx = {"tag": open_tag.group(1), "src": indent, "delta": target - indent}
            out.append(" " * target + stripped)
            continue

        match = LIST_ITEM_RE.match(raw)
        if match:
            # a sibling may be indented a space out; only a clear step in
            # indentation opens or closes a level
            while len(stack) > 1 and indent < stack[-1]["src"] - 1:
                stack.pop()
            if not stack:
                stack.append({"src": indent, "base": 0, "content": 0})
            elif indent >= stack[-1]["src"] + 2:
                stack.append({"src": indent, "base": stack[-1]["content"], "content": 0})
            elif indent < stack[-1]["src"] - 1:
                # Only the outermost level is left and this item sits further
                # left than the one that opened the list - Intercom does this
                # when a list starts indented and later items do not. Re-base
                # the level; popping it would empty the stack and the next
                # line would crash on stack[-1].
                stack[-1] = {"src": indent, "base": 0, "content": 0}

            level = stack[-1]
            marker = match.group("marker")
            marker = (marker + " ") if marker[-1] in ".)" else "- "
            level["content"] = level["base"] + len(marker)
            out.append(" " * level["base"] + marker + match.group("text").rstrip())
            continue

        if HEADING_RE.match(raw) or indent == 0:
            stack = []
            out.append(stripped)
            continue

        # indented prose or screenshot: it continues the current step
        out.append((" " * stack[-1]["content"] + stripped) if stack else raw.rstrip())
    return "\n".join(out)


def notes_to_callouts(body):
    """Turn '**Note:** ...' into <Note>/<Warning>/<Tip>, at the right indent.

    The label is kept as the first thing inside the callout ("**Note:**",
    "**Important:**"), because Mintlify draws an icon but never the word.

    A note inside a numbered step is indented to that step's content column, so
    the callout lines up with the step text instead of resetting to the margin.
    """
    lines = list(split_fences(body))
    out, i, in_callout = [], 0, 0
    while i < len(lines):
        line, fenced = lines[i]

        # never re-wrap a callout this function produced on an earlier run
        if not fenced and CALLOUT_OPEN_RE.match(line):
            in_callout += 1
        elif not fenced and CALLOUT_CLOSE_RE.match(line):
            in_callout = max(0, in_callout - 1)

        m = NOTE_RE.match(line) if (not fenced and not in_callout) else None
        if not m:
            out.append(line)
            i += 1
            continue

        label = (m.group("a") or m.group("b") or "note").lower()
        indent = m.group("indent").replace("\t", "    ")
        content = [m.group("body").strip()] if m.group("body").strip() else []
        i += 1

        # "**Note:**" on its own line introduces the bullet list beneath it
        if not content:
            while i < len(lines) and not lines[i][0].strip():
                i += 1
            while i < len(lines) and lines[i][0].strip() and not lines[i][1]:
                nxt = lines[i][0]
                if HEADING_RE.match(nxt) or NOTE_RE.match(nxt):
                    break
                content.append(nxt.rstrip())
                i += 1
            base = min((len(l) - len(l.lstrip()) for l in content if l.strip()), default=0)
            content = [l[base:] if len(l) > base else l.strip() for l in content]

        if not content:
            continue

        component = CALLOUT_FOR.get(label, "Note")
        tag = "**%s:**" % CALLOUT_LABEL.get(label, label.title())

        # A single sentence reads best with the label inline; a bullet list
        # needs the label on its own line or the first bullet swallows it.
        first = content[0].lstrip()
        if len(content) == 1 and not first.startswith(("-", "*", "+")):
            content = ["%s %s" % (tag, first)]
        else:
            content = [tag, ""] + content

        if out and out[-1].strip():
            out.append("")
        out.append(indent + "<" + component + ">")
        out.extend(indent + "  " + l if l.strip() else "" for l in content)
        out.append(indent + "</" + component + ">")
        if i < len(lines) and lines[i][0].strip():
            out.append("")
    return "\n".join(out)


COMPONENT_LABEL = {"Note": "Note", "Info": "Note", "Tip": "Tip",
                   "Warning": "Warning", "Check": "Check", "Danger": "Danger"}
LABELLED_RE = re.compile(r"^[ \t]*\*\*[A-Za-z][A-Za-z ]*:\*\*")


def label_existing_callouts(body):
    """Backfill the label on callouts written before labels were kept.

    Only the component name is available for those, so <Note> becomes
    "**Note:**". Idempotent: a callout whose first line is already a bold
    label is left untouched.
    """
    lines = body.splitlines()
    out, i = [], 0
    while i < len(lines):
        line = lines[i]
        out.append(line)
        m = CALLOUT_OPEN_RE.match(line)
        if not m or line.rstrip().endswith("/>"):
            i += 1
            continue

        i += 1
        # find the first line with content inside this callout
        blanks = []
        while i < len(lines) and not lines[i].strip():
            blanks.append(lines[i])
            i += 1
        if i >= len(lines) or CALLOUT_CLOSE_RE.match(lines[i]):
            out.extend(blanks)
            continue

        out.extend(blanks)
        first = lines[i]
        if LABELLED_RE.match(first):
            out.append(first)
            i += 1
            continue

        tag = "**%s:**" % COMPONENT_LABEL.get(m.group(1), m.group(1))
        indent = first[:len(first) - len(first.lstrip())]
        stripped = first.strip()
        if stripped.startswith(("-", "*", "+")):
            out += [indent + tag, "", first]
        else:
            out.append(indent + tag + " " + stripped)
        i += 1
    return "\n".join(out)


def fix_anchor_links(body):
    """Rewrite Intercom's '#h_e6d165b891' anchors, which 404 in Mintlify.

    The link text usually names the heading it points at, so it is matched
    against the document's own headings. An unmatched link loses its href
    rather than shipping a dead one.
    """
    slugs = [anchor_slug(m.group(2))
             for line, fenced in split_fences(body) if not fenced
             for m in [HEADING_RE.match(line)] if m]
    slugs = [s for s in slugs if s]

    def resolve(match):
        text = match.group(1)
        want = anchor_slug(text)
        if not want:
            return text
        for slug in slugs:
            if slug == want:
                return "[%s](#%s)" % (text, slug)
        for slug in slugs:
            if want in slug or slug in want:
                return "[%s](#%s)" % (text, slug)
        return text

    return re.sub(r"\[([^\]\n]+)\]\(#h_[0-9a-zA-Z_]+\)", resolve, body)


def is_bogus_url(href):
    """True when a link's target is prose that ended up in Intercom's URL box.

    Authors sometimes type a description where the URL goes; Intercom stores it
    verbatim with an https:// bolted on, producing hrefs like
    "https://Landing page for the user-portal. Displays all the ...".

    Only the authority is examined, never the rest of the URL. Percent-encoded
    spaces are perfectly legal in a path or a fragment - Intercom's own deep
    links use `#:~:text=Facility%20Code` - and treating those as broken would
    destroy working links.
    """
    match = re.match(r"^https?://([^/?#]*)", href or "", re.I)
    if not match:
        return False
    host = match.group(1)
    if not host:
        return True
    if "%20" in host or " " in host:          # a hostname cannot contain a space
        return True
    host = host.split("@")[-1].split(":")[0]  # drop userinfo and port
    if "." not in host.rstrip("."):           # no dot means no TLD
        return True
    return False


def tidy_links(body):
    """Drop the help-centre suffix from link text, and unlink bogus targets."""
    def fix(match):
        text, href = match.group(1), match.group(2)
        text = re.sub(r"\s*\|\s*Oloid Help Cent(?:er|re)\s*$", "", text, flags=re.I)
        text = text.strip() or match.group(1).strip()
        if is_bogus_url(href):
            # keep what the author wrote, lose the link that would 404
            return text
        return "[%s](%s)" % (text, href)
    return re.sub(r"\[([^\]\n]+)\]\((https?://[^)\s]+)\)", fix, body)


def tidy_entities(body):
    """'Directory &gt; People' reads as source noise; '>' is safe mid-line.

    It is left alone at the start of a line, where markdown would read it as a
    blockquote, and '&lt;' is left escaped because MDX parses '<' as JSX.
    """
    out = []
    for line, fenced in split_fences(body):
        if not fenced:
            # Intercom sprinkles zero-width spaces through pasted content; each
            # one survives as a line of its own and renders as a blank paragraph
            line = line.replace("​", "").replace("‌", "").replace("﻿", "")
            line = line.replace(" ", " ")
            if not line.lstrip().startswith("&gt;"):
                line = line.replace("&gt;", ">")
            # "**OKTA** **ID**" is two runs of bold with a space between
            line = re.sub(r"\*\*([^*\n]+?)\*\* \*\*([^*\n]+?)\*\*", r"**\1 \2**", line)
        out.append(line)
    return "\n".join(out)


def tidy_blank_lines(body):
    out, blanks = [], 0
    for line, fenced in split_fences(body):
        line = line.rstrip() if not fenced else line
        if not fenced and not line.strip():
            blanks += 1
            if blanks > 1:
                continue
        else:
            blanks = 0
        out.append(line)
    return "\n".join(out).strip()


def audit_sections(body):
    """Report which template sections the page has, without inventing any."""
    found = set()
    for line, fenced in split_fences(body):
        m = HEADING_RE.match(line) if not fenced else None
        if not m or len(m.group(1)) != 2:
            continue
        text = m.group(2).strip()
        if text in TEMPLATE_SECTIONS:
            found.add(text)
        elif re.match(r"^steps?\b|^how to\b|^procedure\b", text, re.I):
            found.add("Steps")
    missing = [s for s in TEMPLATE_SECTIONS
               if s not in found and s not in OPTIONAL_SECTIONS]
    return {"found": [s for s in TEMPLATE_SECTIONS if s in found], "missing": missing}


def apply_template(body, mirror=False):
    """Normalise one converted article. Returns (body, keywords, audit).

    Everything here is mechanical - entity cleanup, list columns, callouts,
    dead anchors - and applies in both modes. Only heading rewriting differs:
    with `mirror=True` the article keeps oloid.help's own section structure,
    and the audit becomes a report of what is there rather than a checklist of
    what a template demands.
    """
    body, keywords = extract_keywords(body or "")
    body = normalize_headings(body, mirror=mirror)
    body = frames_to_images(body)
    body = tidy_entities(body)
    body = tidy_links(body)
    # columns must be correct before callouts are placed, because a callout is
    # indented to the column of the step it belongs to
    body = reindent_lists(body)
    body = notes_to_callouts(body)
    body = label_existing_callouts(body)
    body = fix_anchor_links(body)
    body = tidy_blank_lines(body)
    return body, keywords, audit_sections(body)


# --------------------------------------------------------------------------
# Slugs and paths
# --------------------------------------------------------------------------

def slugify(value, max_len=70):
    value = html.unescape(str(value or "")).lower()
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    if len(value) > max_len:
        value = value[:max_len].rsplit("-", 1)[0]
    return value or "untitled"


def page_slug(article):
    """Prefer the slug Intercom already uses in the public URL."""
    url = article.get("url") or ""
    tail = urllib.parse.urlparse(url).path.rstrip("/").split("/")[-1]
    tail = re.sub(r"^\d+-", "", tail)  # drop the leading article id
    return slugify(tail or article.get("title"))


# --------------------------------------------------------------------------
# MDX file
# --------------------------------------------------------------------------

def short_title(title, limit=48):
    """Intercom titles run well past 100 characters, which wrecks the sidebar.

    "Oloid Vault (Chrome / Chromium) - How to Create and Configure ..."
      -> "How to Create and Configure Oloid Vault..."
    """
    text = re.sub(r"\s+", " ", title).strip()
    # drop a leading "Product - " qualifier; the menu already carries that context
    if " - " in text:
        head, _, tail = text.partition(" - ")
        if len(head) <= 60 and len(tail) >= 12:
            text = tail.strip()
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0].rstrip(" ,.;:-")
    return (cut or text[:limit]) + "..."


def first_sentence(body_mdx, limit=160):
    """Fallback description: the first real prose line of the article."""
    for line in (body_mdx or "").splitlines():
        line = line.strip()
        if not line or line.startswith(("#", "<", "|", "-", ">", "!", "`", "1.")):
            continue
        line = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", line)   # unwrap links
        line = re.sub(r"[*`]+", "", line)                        # drop emphasis
        line = re.sub(r"&#?\w+;", " ", line)                     # drop entities
        line = re.sub(r"\s+", " ", line).strip()
        if len(line) < 25:
            continue
        if len(line) > limit:
            line = line[:limit].rsplit(" ", 1)[0].rstrip(" ,.;:-") + "..."
        return line
    return ""


def build_mdx(article, body_mdx, icon=None, keywords=None):
    title = html.unescape((article.get("title") or "Untitled").strip())
    desc = html.unescape((article.get("description") or "").strip())
    desc = re.sub(r"\s+", " ", desc)[:160] or first_sentence(body_mdx)

    fm = ["---", "title: %s" % json.dumps(title)]
    sidebar = short_title(title)
    if sidebar and sidebar != title:
        fm.append("sidebarTitle: %s" % json.dumps(sidebar))
    if desc:
        fm.append("description: %s" % json.dumps(desc))
    if icon:
        fm.append("icon: %s" % json.dumps(icon))
    if keywords:
        # indexed by Mintlify search; deliberately renders nothing on the page
        fm.append("keywords:")
        fm += ["  - %s" % json.dumps(k) for k in keywords]
    fm += [
        "---",
        "",
        "{/* Source: Intercom article %s - %s */}" % (article.get("id"), article.get("url") or ""),
        "{/* Generated by intercom_to_mintlify.py - re-running overwrites this file. */}",
        "",
        "",
    ]
    return "\n".join(fm) + (body_mdx or "_This article has no body content in Intercom._") + "\n"


# --------------------------------------------------------------------------
# Reformatting pages that are already on disk
# --------------------------------------------------------------------------
#  Re-running the importer needs an Intercom token. --reformat applies the
#  template to the .mdx files already in the repo instead, so a change to the
#  document format can be rolled out without re-fetching every article.
# --------------------------------------------------------------------------

GENERATED_MARKER = "Generated by intercom_to_mintlify.py"


def split_frontmatter(text):
    """Return (frontmatter_lines, body). Frontmatter here is always generated
    by this script, so a line scan is enough and avoids a YAML dependency."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return [], text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return lines[1:i], "\n".join(lines[i + 1:])
    return [], text


def set_frontmatter_keywords(fm_lines, keywords):
    """Replace the keywords block, or leave it alone when there is nothing new.

    On a second --reformat run the body no longer holds a Keywords section
    (the first run moved it up here), so an empty list must not be read as
    "this page has no keywords".
    """
    if not keywords:
        return fm_lines
    out, in_keywords = [], False
    for line in fm_lines:
        if re.match(r"^keywords[ \t]*:", line):
            in_keywords = True
            continue
        if in_keywords:
            if re.match(r"^[ \t]+-[ \t]", line):
                continue
            in_keywords = False
        out.append(line)
    out.append("keywords:")
    out += ["  - %s" % json.dumps(k) for k in keywords]
    return out


def reformat_file(path, dry_run):
    with open(path, "r", encoding="utf-8") as fh:
        original = fh.read()
    if GENERATED_MARKER not in original:
        return None

    fm_lines, body = split_frontmatter(original)
    body, keywords, audit = apply_template(body)
    fm_lines = set_frontmatter_keywords(fm_lines, keywords)
    rebuilt = "---\n" + "\n".join(fm_lines) + "\n---\n\n" + body + "\n"

    changed = rebuilt != original
    if changed and not dry_run:
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(rebuilt)
    return {"path": path, "changed": changed, "keywords": keywords, "audit": audit}


def reformat_tree(root, dry_run):
    results = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames
                       if d not in (".git", "node_modules", "__pycache__", "images")]
        for name in sorted(filenames):
            if not name.endswith(".mdx"):
                continue
            row = reformat_file(os.path.join(dirpath, name), dry_run)
            if row:
                row["rel"] = os.path.relpath(row["path"], root).replace(os.sep, "/")
                results.append(row)
    return results


# --------------------------------------------------------------------------
# docs.json navigation
# --------------------------------------------------------------------------

def migrate_to_tabs(nav):
    """Navigation accepts pages OR tabs, not both. Move any existing top-level
    pages/groups into a tab so nothing is lost."""
    if "tabs" in nav:
        return nav, None
    carried = None
    icon = icon_for(EXISTING_PAGES_TAB)
    if nav.get("groups"):
        carried = {"tab": EXISTING_PAGES_TAB, "groups": nav.pop("groups")}
    elif nav.get("pages"):
        carried = {"tab": EXISTING_PAGES_TAB, "pages": nav.pop("pages")}
    if carried and icon:
        carried["icon"] = icon
    nav["tabs"] = [carried] if carried else []
    return nav, (EXISTING_PAGES_TAB if carried else None)


def apply_theme(docs):
    """Set the theme and turn on breadcrumb eyebrows above page titles."""
    changed = []
    if THEME and docs.get("theme") != THEME:
        docs["theme"] = THEME
        changed.append("theme=%s" % THEME)
    if EYEBROWS:
        styling = docs.setdefault("styling", {})
        if styling.get("eyebrows") != EYEBROWS:
            styling["eyebrows"] = EYEBROWS
            changed.append("eyebrows=%s" % EYEBROWS)
    if FONTS:
        if docs.get("fonts") != FONTS:
            docs["fonts"] = FONTS
            families = sorted({f["family"] for f in FONTS.values() if isinstance(f, dict)}) \
                if "family" not in FONTS else [FONTS["family"]]
            changed.append("fonts=%s" % "+".join(families))
    elif "fonts" in docs:
        # FONTS is deliberately empty: the family is a system stack set in
        # style.css, and a leftover docs.json webfont would override it.
        docs.pop("fonts")
        changed.append("fonts=system-ui (from style.css)")
    changed += strip_placeholder_chrome(docs)
    return changed


def is_placeholder(url):
    """True for a starter-kit link: a mintlify.com URL, or a social account
    whose handle is mintlify (https://x.com/mintlify and friends)."""
    url = str(url or "").lower().rstrip("/")
    if any(host in url for host in PLACEHOLDER_HOSTS):
        return True
    return url.endswith("/mintlify") or url.endswith("/company/mintlify")


def strip_placeholder_chrome(docs):
    """Drop starter-kit navigation that still points at mintlify.com.

    Every removal is reported so nothing disappears silently, and a link to a
    real Oloid URL is never touched.
    """
    removed = []

    if docs.get("name") in (None, "", "Mintlify Starter Kit") and SITE_NAME:
        if docs.get("name") != SITE_NAME:
            removed.append("name %r -> %r" % (docs.get("name"), SITE_NAME))
            docs["name"] = SITE_NAME

    nav = docs.get("navigation", {})
    anchors = nav.get("global", {}).get("anchors")
    if isinstance(anchors, list):
        keep = [a for a in anchors if not is_placeholder(a.get("href"))]
        for a in anchors:
            if a not in keep:
                removed.append("anchor %r" % a.get("anchor"))
        if keep:
            nav["global"]["anchors"] = keep
        else:
            nav.get("global", {}).pop("anchors", None)
            if not nav.get("global"):
                nav.pop("global", None)

    navbar = docs.get("navbar", {})
    links = navbar.get("links")
    if isinstance(links, list):
        keep = [l for l in links if not is_placeholder(l.get("href"))]
        for l in links:
            if l not in keep:
                removed.append("navbar link %r" % l.get("label"))
        if keep:
            navbar["links"] = keep
        else:
            navbar.pop("links", None)
    primary = navbar.get("primary")
    if isinstance(primary, dict) and is_placeholder(primary.get("href")):
        removed.append("navbar button %r" % primary.get("label"))
        navbar.pop("primary", None)
    if not navbar:
        docs.pop("navbar", None)

    socials = docs.get("footer", {}).get("socials")
    if isinstance(socials, dict):
        keep = {k: v for k, v in socials.items() if not is_placeholder(v)}
        for k in socials:
            if k not in keep:
                removed.append("footer social %r" % k)
        if keep:
            docs["footer"]["socials"] = keep
        else:
            docs.get("footer", {}).pop("socials", None)
            if not docs.get("footer"):
                docs.pop("footer", None)

    if CONTEXTUAL_OPTIONS:
        current = docs.get("contextual", {}).get("options")
        if current != CONTEXTUAL_OPTIONS:
            removed.append("contextual options %d -> %d"
                           % (len(current or []), len(CONTEXTUAL_OPTIONS)))
            docs.setdefault("contextual", {})["options"] = list(CONTEXTUAL_OPTIONS)

    return removed


def write_style_css(root, dry_run):
    """Write style.css, which Mintlify auto-loads from the repo root.

    An existing file is only replaced when this script wrote it; a hand-written
    style.css is left alone and reported instead of being clobbered.
    """
    path = os.path.join(root, "style.css")
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fh:
            existing = fh.read()
        if STYLE_MARKER not in existing:
            return "skipped (style.css exists and was not generated by this script)"
        if existing.strip() == STYLE_CSS.strip():
            return "unchanged"
    if dry_run:
        return "would write"
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(STYLE_CSS.lstrip("\n"))
    return "written"


def icon_for(label):
    return ICONS.get(label)


def backfill_icons(nav):
    """Attach icons from ICONS onto navigation entries that already exist.

    Used by --config-only so theme/icon changes can be applied to a docs.json
    without re-fetching every article.
    """
    added = []

    def visit(node):
        if isinstance(node, dict):
            for key in ("tab", "item", "group"):
                label = node.get(key)
                if isinstance(label, str) and "icon" not in node:
                    ic = icon_for(label)
                    if ic:
                        node["icon"] = ic
                        added.append(label)
            for value in node.values():
                visit(value)
        elif isinstance(node, list):
            for value in node:
                visit(value)

    visit(nav)
    return added


def find_or_create(items, key, value, extra):
    for entry in items:
        if entry.get(key) == value:
            # backfill an icon onto an entry created before ICONS knew about it
            if "icon" in extra and "icon" not in entry:
                entry["icon"] = extra["icon"]
            return entry, False
    entry = {key: value}
    entry.update(extra)
    items.append(entry)
    return entry, True


def upsert_page(nav, tab, menu, group, page_path):
    """Ensure tabs[tab].menu[menu].groups[group].pages contains page_path."""
    def with_icon(label, base):
        ic = icon_for(label)
        return dict(base, icon=ic) if ic else dict(base)

    tabs = nav.setdefault("tabs", [])
    tab_entry, _ = find_or_create(tabs, "tab", tab, with_icon(tab, {"menu": []}))

    # a tab created earlier by migration may hold pages/groups instead of menu
    if "menu" not in tab_entry:
        tab_entry["menu"] = []
    menu_list = tab_entry["menu"]

    menu_entry, _ = find_or_create(menu_list, "item", menu, with_icon(menu, {"groups": []}))
    if "groups" not in menu_entry:
        menu_entry["groups"] = []

    group_entry, _ = find_or_create(
        menu_entry["groups"], "group", group, with_icon(group, {"pages": []}))
    pages = group_entry.setdefault("pages", [])

    if page_path in pages:
        return "already linked"
    pages.append(page_path)
    return "linked"


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def download_image(url, root, article_id, dry_run, stats):
    """Save a remote image locally and return the docs-absolute path.

    Intercom serves images from signed CDN URLs whose ?expires= is only hours
    away, so the signature is stripped and the bytes are stored in the repo.
    Files are namespaced per article to avoid collisions between articles that
    happen to use the same original filename.
    """
    clean = url.split("?")[0]
    parsed = urllib.parse.urlparse(clean)
    name = urllib.parse.unquote(os.path.basename(parsed.path)) or "image"
    name = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-.") or "image"
    stem, dot, ext = name.rpartition(".")
    if not dot:
        stem, ext = name, "png"

    # Intercom names almost every screenshot "image.png", so the basename alone
    # collides and articles end up sharing one file. The URL digest keeps each
    # distinct image separate while staying stable across re-runs.
    digest = hashlib.sha1(clean.encode("utf-8")).hexdigest()[:8]
    name = "%s-%s.%s" % (stem[:48], digest, ext.lower())

    rel = "/%s/%s/%s" % (IMAGE_DIR.strip("/"), article_id, name)
    dest = os.path.join(root, IMAGE_DIR, str(article_id), name)

    if dry_run:
        return rel
    if os.path.exists(dest):
        stats["reused"] += 1
        stats["bytes"] += os.path.getsize(dest)
        return rel
    try:
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        req = urllib.request.Request(clean, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = resp.read()
        with open(dest, "wb") as fh:
            fh.write(data)
        stats["saved"] += 1
        stats["bytes"] += len(data)
        if len(data) > MAX_IMAGE_BYTES:
            stats["oversize"].append((rel, len(data)))
        elif len(data) > 5 * 1024 * 1024:
            stats["large"].append((rel, len(data)))
        return rel
    except Exception as exc:  # noqa: BLE001 - an image is never worth aborting for
        sys.stderr.write("  ! image failed (%s), keeping remote URL\n" % exc)
        stats["failed"].append(url)
        return url


# --------------------------------------------------------------------------
# Navigation-driven migration
# --------------------------------------------------------------------------
#  navigation.json owns the tree: every group lists the Intercom collections
#  ("Product :: Collection") whose articles belong in it. This mode fetches
#  every article, resolves its collection, and writes the page into that
#  group's directory. docs.json is not touched here - build_nav.py rebuilds it
#  from whatever .mdx files end up on disk.
#
#  Three GET endpoints, and nothing else:
#      GET /help_center/collections   the Product / Section tree
#      GET /articles                  every article summary, 150 per page
#      GET /articles/{id}             the full body
#  This script never calls POST, PUT or DELETE against Intercom.
# --------------------------------------------------------------------------

NAV_FILE = "navigation.json"
PLACEHOLDER_MARK = "This section is a placeholder."


def _helpers():
    """intercom_fetch.py owns the HTTP and pagination layer, build_nav.py owns
    the tree walk. Import both rather than keeping a second copy of either."""
    import build_nav
    import intercom_fetch
    return build_nav, intercom_fetch


def nav_group_dirs(nav, build_nav):
    """{normalised 'Product :: Collection': [group directory, ...]}

    A collection can be listed in more than one group - Healthcare appears
    under Windows > Version 1 and again under Resources > Industries. The first
    directory owns the file on disk; the second group picks the same pages up
    through its `pages_from` key, so the article exists once and is listed
    twice.
    """
    mapping = {}
    for grp, slug_parts, _crumbs in build_nav.iter_groups(nav):
        directory = os.path.join(*slug_parts) if slug_parts else "."
        for coll in grp.get("collections") or []:
            mapping.setdefault(build_nav.norm(coll), []).append(directory)
    return mapping


def drop_repeated_title(body, title):
    """Drop a leading heading that just restates the article title.

    Intercom keeps the title out of `body`, but a few articles open with it
    anyway. The frontmatter title already renders as the page's H1, and
    oloid.help never shows it twice.
    """
    lines = (body or "").lstrip("\n").splitlines()
    if not lines:
        return body
    m = HEADING_RE.match(lines[0])
    if not m:
        return body
    squash = lambda s: re.sub(r"[^a-z0-9]+", "", (s or "").lower())
    if squash(clean_heading_text(m.group(2))) != squash(title):
        return body
    return "\n".join(lines[1:]).lstrip("\n")


def drop_placeholder(directory):
    """Remove a group's generated overview once real articles have landed."""
    path = os.path.join(directory, "overview.mdx")
    if not os.path.exists(path):
        return False
    with open(path, "r", encoding="utf-8") as fh:
        if PLACEHOLDER_MARK not in fh.read():
            return False          # somebody wrote a real overview; keep it
    os.remove(path)
    return True


def migrate(args, root):
    """Fetch every article and file it under the navigation."""
    build_nav, fetchlib = _helpers()

    nav_path = os.path.join(root, NAV_FILE)
    if not os.path.exists(nav_path):
        sys.stderr.write("ERROR: no %s - run build_nav.py first\n" % nav_path)
        return 2
    with open(nav_path, "r", encoding="utf-8") as fh:
        nav = json.load(fh)
    mapping = nav_group_dirs(nav, build_nav)

    sys.stderr.write("[1/3] GET /help_center/collections ...\n")
    _raw, paths = fetchlib.fetch_collections(args.api_key)
    sys.stderr.write("      %d collections\n" % len(paths))

    sys.stderr.write("[2/3] GET /articles ...\n")
    summaries = fetchlib.fetch_article_list(args.api_key, args.limit)
    sys.stderr.write("      %d articles\n" % len(summaries))

    sys.stderr.write("[3/3] GET /articles/{id} ...\n")
    cache = os.path.join(root, args.cache_dir, "articles")
    articles = fetchlib.fetch_article_bodies(args.api_key, summaries, cache,
                                             refresh=args.refresh)

    img_stats = {"saved": 0, "reused": 0, "bytes": 0,
                 "large": [], "oversize": [], "failed": []}
    written, skipped_empty, unmapped = [], [], {}
    used_paths, touched = {}, set()

    for art in articles:
        article_id = str(art.get("id"))
        product, collection, _full = fetchlib.resolve_placement(art, paths)
        key = build_nav.norm("%s :: %s" % (product, collection))

        dirs = mapping.get(key)
        if not dirs:
            unmapped.setdefault("%s :: %s" % (product, collection), []).append(article_id)
            continue

        title = html.unescape((art.get("title") or "Untitled").strip())
        if not (art.get("body") or "").strip():
            skipped_empty.append((article_id, title))
            continue

        on_image = None
        if not args.no_download_images:
            def on_image(u, _id=article_id):
                return download_image(u, root, _id, args.dry_run, img_stats)

        body_mdx, images, videos = html_to_mdx(
            art.get("body") or "", on_image=on_image,
            alt_prefix=short_title(title, 40))
        body_mdx, keywords, audit = apply_template(body_mdx, mirror=True)
        body_mdx = drop_repeated_title(body_mdx, title)

        if not body_mdx.strip():
            skipped_empty.append((article_id, title + "  (body did not convert)"))
            continue

        directory = dirs[0]
        slug = page_slug(art)
        rel = "%s/%s" % (directory.replace(os.sep, "/"), slug)
        if rel in used_paths and used_paths[rel] != article_id:
            slug = "%s-%s" % (slug, article_id)      # two articles, one slug
            rel = "%s/%s" % (directory.replace(os.sep, "/"), slug)
        used_paths[rel] = article_id

        if not args.dry_run:
            abs_path = os.path.join(root, directory, slug + ".mdx")
            os.makedirs(os.path.dirname(abs_path), exist_ok=True)
            with open(abs_path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(build_mdx(art, body_mdx, icon=DEFAULT_PAGE_ICON,
                                   keywords=keywords))
        touched.add(directory)
        written.append({"id": article_id, "title": title, "path": rel + ".mdx",
                        "words": len(body_mdx.split()), "images": len(images),
                        "videos": len(videos), "sections": audit.get("found", []),
                        "collection": "%s :: %s" % (product, collection)})

        if len(written) % 100 == 0:
            sys.stderr.write("      wrote %d pages\n" % len(written))

    dropped = 0
    if not args.dry_run:
        for directory in sorted(touched):
            dropped += 1 if drop_placeholder(directory) else 0

    write_style_css(root, args.dry_run)

    print("")
    print("=" * 72)
    print("Intercom -> Mintlify%s" % ("  (DRY RUN - nothing written)" if args.dry_run else ""))
    print("=" * 72)
    print("Fetched      : %d articles in %d collections" % (len(articles), len(paths)))
    print("Written      : %d pages across %d groups" % (len(written), len(touched)))
    print("Skipped      : %d with an empty body" % len(skipped_empty))
    print("Placeholders : %d removed (group now has real pages)" % dropped)
    print("Images       : %d saved, %d reused, %d failed"
          % (img_stats["saved"], img_stats["reused"], len(img_stats["failed"])))
    if unmapped:
        total = sum(len(v) for v in unmapped.values())
        print("")
        print("UNMAPPED - %d collection(s), %d article(s) not written:"
              % (len(unmapped), total))
        for coll, ids in sorted(unmapped.items(), key=lambda kv: -len(kv[1])):
            print("   %4d  %s" % (len(ids), coll))
        print("   Add these to navigation.json, then re-run.")
    if skipped_empty:
        print("")
        print("EMPTY IN INTERCOM - %d:" % len(skipped_empty))
        for article_id, title in skipped_empty[:25]:
            print("   %-10s %s" % (article_id, title[:70]))
        if len(skipped_empty) > 25:
            print("   ... and %d more" % (len(skipped_empty) - 25))
    print("")

    if not args.dry_run and not args.no_nav:
        print("Rebuilding docs.json ...")
        import subprocess
        subprocess.call([sys.executable, os.path.join(root, "build_nav.py")])
    else:
        print("Next: python build_nav.py     # rebuild docs.json from what is on disk")
    return 0


def main():
    parser = argparse.ArgumentParser(
        description="Fetch Intercom articles by ID and wire them into Mintlify docs.json."
    )
    parser.add_argument(
        "--api-key", default=None,
        help="Intercom bearer token. Falls back to $INTERCOM_API_KEY, then "
             "./.intercom_token, then the API_KEY constant.",
    )
    parser.add_argument("--root", default=".", help="Mintlify project root (default: .)")
    parser.add_argument("--docs-json", default=None, help="Path to docs.json (default: <root>/docs.json)")
    parser.add_argument("--no-download-images", action="store_true",
                        help="Hotlink the Intercom CDN instead of saving images locally. "
                             "Not recommended: Intercom's image URLs are signed and expire.")
    parser.add_argument("--dry-run", action="store_true", help="Report only; write nothing.")
    parser.add_argument("--config-only", action="store_true",
                        help="Only apply theme, breadcrumbs and icons to docs.json. "
                             "Fetches nothing and leaves existing pages untouched.")
    parser.add_argument("--reformat", action="store_true",
                        help="Re-apply the document template and style.css to the .mdx "
                             "pages already in the repo. Needs no Intercom token.")
    parser.add_argument("--migrate", action="store_true",
                        help="Fetch EVERY article and file it under navigation.json. "
                             "Uses GET /help_center/collections, /articles and "
                             "/articles/{id} - no write endpoints, ever.")
    parser.add_argument("--limit", type=int, default=None,
                        help="--migrate: stop after N articles (smoke test).")
    parser.add_argument("--refresh", action="store_true",
                        help="--migrate: ignore the cache and re-fetch every article.")
    parser.add_argument("--cache-dir", default="intercom_export",
                        help="--migrate: where per-article JSON is cached "
                             "(default: intercom_export).")
    parser.add_argument("--no-nav", action="store_true",
                        help="--migrate: skip the build_nav.py run at the end.")
    args = parser.parse_args()

    try:
        import intercom_fetch
        args.api_key = intercom_fetch.resolve_token(args.api_key)
    except ImportError:
        args.api_key = (args.api_key
                        or os.environ.get("INTERCOM_API_KEY")
                        or os.environ.get("INTERCOM_TOKEN")
                        or API_KEY)

    if args.reformat:
        root = os.path.abspath(args.root)
        rows = reformat_tree(root, args.dry_run)
        style_status = write_style_css(root, args.dry_run)

        docs_path = args.docs_json or os.path.join(root, "docs.json")
        theme_changes = []
        if os.path.exists(docs_path):
            with open(docs_path, "r", encoding="utf-8") as fh:
                docs = json.load(fh)
            theme_changes = apply_theme(docs)
            if theme_changes and not args.dry_run:
                with open(docs_path, "w", encoding="utf-8", newline="\n") as fh:
                    json.dump(docs, fh, indent=2, ensure_ascii=False)
                    fh.write("\n")

        print("")
        print("=" * 72)
        print("Reformat to template%s" % ("  (DRY RUN - nothing written)" if args.dry_run else ""))
        print("=" * 72)
        print("Pages     : %d generated, %d rewritten"
              % (len(rows), sum(1 for r in rows if r["changed"])))
        print("style.css : %s" % style_status)
        if theme_changes:
            print("docs.json :")
            for change in theme_changes:
                print("              - %s" % change)
        print("")
        for r in rows:
            print("%s %s" % ("~~" if r["changed"] else "ok", r["rel"]))
            print("     sections : %s" % (" > ".join(r["audit"]["found"]) or "none recognised"))
            if r["audit"]["missing"]:
                print("     MISSING  : %s  (add by hand; nothing was invented)"
                      % ", ".join(r["audit"]["missing"]))
            print("     keywords : %s" % (", ".join(r["keywords"])
                                          or "already in frontmatter (none left in body)"))
            print("")
        print("Preview locally:")
        print("    mint dev          # http://localhost:3000")
        print("")
        return 0

    if args.migrate:
        if not args.api_key:
            parser.error(
                "--migrate needs a bearer token. Either:\n"
                "  1. put it in ./.intercom_token   (gitignored, one line), or\n"
                "  2. $env:INTERCOM_API_KEY = 'your_token'   (PowerShell), or\n"
                "  3. python intercom_to_mintlify.py --migrate --api-key your_token"
            )
        return migrate(args, os.path.abspath(args.root))

    if not args.api_key and not args.config_only:
        parser.error(
            "No bearer token. Either:\n"
            "  1. set API_KEY = \"your_token\" at the top of this file, or\n"
            "  2. $env:INTERCOM_API_KEY = 'your_token'   (PowerShell), or\n"
            "  3. python intercom_to_mintlify.py --api-key your_token"
        )

    root = os.path.abspath(args.root)
    docs_path = args.docs_json or os.path.join(root, "docs.json")
    if not os.path.exists(docs_path):
        sys.stderr.write("ERROR: no docs.json at %s\n" % docs_path)
        return 2

    with open(docs_path, "r", encoding="utf-8") as fh:
        docs = json.load(fh)
    theme_changes = apply_theme(docs)
    nav = docs.setdefault("navigation", {})
    nav, migrated = migrate_to_tabs(nav)

    if args.config_only:
        icons_added = backfill_icons(nav)
        style_status = write_style_css(root, args.dry_run)
        if not args.dry_run:
            with open(docs_path, "w", encoding="utf-8", newline="\n") as fh:
                json.dump(docs, fh, indent=2, ensure_ascii=False)
                fh.write("\n")
        print("")
        print("=" * 72)
        print("docs.json refresh%s" % ("  (DRY RUN)" if args.dry_run else ""))
        print("=" * 72)
        print("Applied  : %s" % (", ".join(theme_changes) or "no theme change needed"))
        if migrated:
            print("Migrated : top-level navigation moved into the %r tab" % migrated)
        print("Icons    : %s" % (", ".join(icons_added) if icons_added
                                 else "none added (all entries already had one)"))
        print("style.css: %s" % style_status)
        print("File     : %s" % docs_path)
        print("")
        print("Note: existing .mdx pages are untouched. Re-run without --config-only")
        print("      to regenerate them with sidebarTitle, icons and image alt text.")
        print("")
        return 0

    results = []
    used_paths = {}
    img_stats = {"saved": 0, "reused": 0, "bytes": 0,
                 "large": [], "oversize": [], "failed": []}

    for spec in ARTICLE_MAP:
        article_id = spec["id"]
        row = {"id": article_id, "tab": spec["tab"], "menu": spec["menu"],
               "group": spec["group"], "status": "", "title": "", "path": "",
               "words": 0, "images": 0, "videos": 0}
        try:
            article = fetch_article(article_id, args.api_key)
        except IntercomError as exc:
            row["status"] = "FAILED: %s" % exc
            results.append(row)
            sys.stderr.write("  ! %s\n" % exc)
            continue

        title = html.unescape((article.get("title") or "Untitled").strip())
        row["title"] = title

        on_image = None
        if not args.no_download_images:
            def on_image(u, _id=article_id):
                return download_image(u, root, _id, args.dry_run, img_stats)

        body_mdx, images, videos = html_to_mdx(
            article.get("body") or "", on_image=on_image, alt_prefix=short_title(title, 40))
        body_mdx, keywords, audit = apply_template(body_mdx)
        row["keywords"] = keywords
        row["audit"] = audit
        row["words"] = len(body_mdx.split())
        row["images"] = len(images)
        row["videos"] = len(videos)

        rel_dir = os.path.join(slugify(spec["tab"]), slugify(spec["menu"]), slugify(spec["group"]))
        slug = page_slug(article)
        nav_path = "%s/%s" % (rel_dir.replace(os.sep, "/"), slug)
        if nav_path in used_paths and used_paths[nav_path] != article_id:
            slug = "%s-%s" % (slug, article_id)
            nav_path = "%s/%s" % (rel_dir.replace(os.sep, "/"), slug)
        used_paths[nav_path] = article_id

        abs_path = os.path.join(root, rel_dir, slug + ".mdx")
        row["path"] = nav_path + ".mdx"

        if not article.get("body"):
            row["status"] = "EMPTY BODY"
        elif not body_mdx:
            row["status"] = "BODY DID NOT CONVERT"
        else:
            row["status"] = "OK"

        if not args.dry_run:
            os.makedirs(os.path.dirname(abs_path), exist_ok=True)
            with open(abs_path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(build_mdx(article, body_mdx,
                                   icon=spec.get("icon", DEFAULT_PAGE_ICON),
                                   keywords=keywords))

        link = upsert_page(nav, spec["tab"], spec["menu"], spec["group"], nav_path)
        row["nav"] = link
        results.append(row)

    style_status = write_style_css(root, args.dry_run)

    if not args.dry_run:
        with open(docs_path, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(docs, fh, indent=2, ensure_ascii=False)
            fh.write("\n")

    # ---------------------------- report ----------------------------------
    print("")
    print("=" * 72)
    print("Intercom -> Mintlify%s" % ("  (DRY RUN - nothing written)" if args.dry_run else ""))
    print("=" * 72)
    if theme_changes:
        print("Applied    : %s" % ", ".join(theme_changes))
    if migrated:
        print("Moved existing top-level navigation into the %r tab." % migrated)
    if theme_changes or migrated:
        print("")

    ok = [r for r in results if r["status"] == "OK"]
    bad = [r for r in results if r["status"] != "OK"]

    print("Requested : %d" % len(ARTICLE_MAP))
    print("Fetched   : %d" % len(ok))
    print("Problems  : %d" % len(bad))
    print("")
    for r in results:
        mark = "OK " if r["status"] == "OK" else "!! "
        print("%s%s" % (mark, r["title"] or "(no title)"))
        print("     id      : %s" % r["id"])
        print("     nav     : %s > %s > %s" % (r["tab"], r["menu"], r["group"]))
        print("     file    : %s" % r["path"])
        print("     content : %d words, %d image(s), %d video(s)"
              % (r["words"], r["images"], r["videos"]))
        audit = r.get("audit") or {}
        if audit:
            print("     sections: %s" % (" > ".join(audit.get("found") or []) or "none recognised"))
            if audit.get("missing"):
                print("     MISSING : %s  (add by hand; nothing was invented)"
                      % ", ".join(audit["missing"]))
        if r.get("keywords"):
            print("     keywords: %s" % ", ".join(r["keywords"]))
        print("     status  : %s (%s)" % (r["status"], r.get("nav", "-")))
        print("")

    if not args.no_download_images:
        mb = img_stats["bytes"] / (1024.0 * 1024.0)
        print("Images    : %d saved, %d already present, %.1f MB total"
              % (img_stats["saved"], img_stats["reused"], mb))
        for rel, size in img_stats["oversize"]:
            print("   OVER 20MB LIMIT: %s (%.1f MB) - Mintlify will reject this; "
                  "compress it or host it on a CDN" % (rel, size / (1024.0 * 1024.0)))
        for rel, size in img_stats["large"]:
            print("   large  : %s (%.1f MB)" % (rel, size / (1024.0 * 1024.0)))
        for url in img_stats["failed"]:
            print("   FAILED : %s (left as remote URL)" % url[:90])
        print("")

    if bad:
        print("NOT imported cleanly:")
        for r in bad:
            print("   - %s: %s" % (r["id"], r["status"]))
        print("")

    print("docs.json : %s" % docs_path)
    print("style.css : %s" % style_status)
    print("")
    print("Preview locally:")
    print("    mint dev          # http://localhost:3000")
    print("")
    return 1 if bad else 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except IntercomError as exc:
        sys.stderr.write("\nERROR: %s\n" % exc)
        sys.exit(2)
    except KeyboardInterrupt:
        sys.stderr.write("\nInterrupted.\n")
        sys.exit(130)
